name: Quarto Publish

on:
  push:
    branches: main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.4.550"

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "knitr", "ggplot2"))'
          # Add more packages if your slides need them
          # e.g. Rscript -e 'install.packages(c("ggplot2", "dplyr"))'

      - name: Render Quarto Project
        run: quarto render

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

